project_id = "hevbjzdahldvijwqtqcx"

[functions.pesapal-payment]
verify_jwt = false

[functions.pesapal-ipn]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false