[build]
  command = "npm run build"
  publish = "build" # Change to "dist" if your build output is dist/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
