[build]
  publish = "dist" # or "build" or "out" depending on your framework
  functions = "netlify/functions"

[[redirects]]
  from = "/functions/pesapal-ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200

[[redirects]]
  from = "/.netlify/functions/pesapal-ipn"
  to = "https://siletoexpress.netlify.app/.netlify/functions/pesapal-ipn"
  status = 200
  force = true
