[build]
  publish = "dist" # change to "build" or "out" if that's your framework's output dir
  functions = "netlify/functions"

[[redirects]]
  from = "/functions/pesapal-ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200

[[redirects]]
  from = "/.netlify/functions/pesapal-ipn"
  to = "https://siletoexpress.netlify.app/.netlify/functions/pesapal-ipn"
  status = 200
  force = true
