[build]
  publish = "dist" # Change to "build" or "out" if your framework uses a different output dir
  functions = "netlify/functions"

# Redirect for PesaPal IPN
[[redirects]]
  from = "/functions/pesapal-ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200

# Force direct access to Netlify Function
[[redirects]]
  from = "/.netlify/functions/pesapal-ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200
  force = true
