[build]
  publish = "dist" # Change to "build" or "out" if your framework outputs there
  functions = "netlify/functions"

[[redirects]]
  from = "/pesapal-ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200
