[build]
  publish = "dist" # or "build" or "out" depending on your framework
  functions = "netlify/functions"

[[redirects]]
  from = "/pesapal-ipn"
  to = "/.netlify/functions/pesapal-ipn"
  status = 200
  force = true
